### ISSUE TITLE
can i ask the model to choose which of the voices sound more natural?

### ISSUE THREAD

**Issue by s-j-chung** [OpenMOSS/AnyGPT#16]
Hi, I would like to use this multimodal model to do MOS (mean opinion score) -ish task for me.
Is it supported in current version?
I think not according to the documents, but if yes, please let me know. 
Thanks!

**Comment by JunZhan2000** [comment]
To my understanding, MOS is a method for scoring voice quality. If that is the case, then this model currently cannot perform this task.

**Comment by s-j-chung** [comment]
Thanks for your kind prompt response!
