### ISSUE TITLE
text chat is not so good.

### ISSUE THREAD

**Issue by mixiazhiyang** [OpenMOSS/AnyGPT#17]
![image](https://github.com/OpenMOSS/AnyGPT/assets/42180243/e6367255-a45f-49c3-b41d-420576af24ac)
it's like no intelligence. Am I wrongly prompting?

**Comment by mixiazhiyang** [comment]
besides, do you provide any interface, like gradio, or something showed in your demo page? Thank you!

**Comment by JunZhan2000** [comment]
First, this model is primarily trained on English data, so we recommend communicating in English. Secondly, it focuses more on multimodal dialogue capabilities, and we did not include pure text instruction data in its training.
