### ISSUE TITLE
请教一下关于AnyGPT模型预训练的一些问题

### ISSUE THREAD

**Issue by shihuai** [OpenMOSS/AnyGPT#28]
您好，感谢你们这么好的工作👍。最近在了解AnyGPT论文和相关代码的细节，有几个关于模型预训练的疑问想请教一下：

1. 在论文中提到使用到的多模态数据集有：text、image、speech、music，但在项目代码中还有audio这一模态，这和论文提到有些不一样，想问一下audio这类数据是什么类型的数据呢？
2. 在模型预训练的时候，speech离散化之后，只取了第一个量化器的token输入到LLM中，但关于music和audio，输入的所有量化器的token，这里是因为直接使用8个speech的量化器作为输入去训练LLM会比较困难吗，还是什么？
3. 在论文中“Apart from reshaping the embedding matrix and prediction layer, the rest of the language model remains unaltered.”，这里对embedding和predict layer进行调整是因为引入了其它模态的token，而LLM部分保持不动是指在预训练阶段，LLM的权重也是冻结的吗？

**Comment by JunZhan2000** [comment]
1. audio指的是audio effect或者说general audio，是之前的一些尝试
2. speech这么做是为了缩短训练长度，序列太长训练会比较困难，但能这么做主要是因为speechtokenizer实现了语音内容和副语言学信息的解耦
3. 是因为引入了token；这里只是指结构不变，权重在两个阶段都是全量训练的

**Comment by shihuai** [comment]
嗯嗯，感谢解答🙏
