### ISSUE TITLE
Does AnyGPT support multi images input?

### ISSUE THREAD

**Issue by QAQdev** [OpenMOSS/AnyGPT#43]
Thanks for your great work!

I am trying to apply AnyGPT on videos, since I need to clip video into frames as multi-images input for AnyGPT, I want to ask that:

- Does AnyGPT support multi-images input?
- What is the context length for AnyGPT?
-How many tokens will each image have?

Based on these, I could calculate a maximum input frames for AnyGPT!

Very looking forward to your reply! @JunZhan2000 Thanks in advance!

**Comment by OffbeatYiranZhao** [comment]
您好，AnyGPT 是否支持多张图片输入以及支持token长度 这个问题您有答案了吗？
